'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const M = require('../space-model.js');
const root = path.resolve(__dirname, '..');
const dataPath = path.join(root, 'data/juris-space.json');
const dataBytes = fs.readFileSync(dataPath);
const data = JSON.parse(dataBytes);
M.validateData(data);
const preferred = ['UNREAL','MORROWIND','FORTUNA','SCARLET','LEARNPORTAL','LEARNSTUDIO','REALMS','RESEARCH','SCARLET_SITE','LEARNSTUDIO_SITE','VAULT','KEEPER','BIRTH','PROPOSAL','PUBLIC_KIT','PROFILE','SPACE'];
const projects = [...data.projects].sort((a,b) => preferred.indexOf(a.id) - preferred.indexOf(b.id));
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = {worlds:'◌', learning:'↗', research:'✦', tools:'⌘', archive:'≡'};
const cards = projects.map(p => `        <article class="project-card" data-project="${esc(p.id)}" data-group="${esc(p.group)}" data-selected="${p.id === data.defaultProject}"><div class="card-top"><span class="card-symbol" aria-hidden="true">${icons[p.group]}</span><span class="card-tag" data-card-tag>${esc(p.tag)}</span></div><h3>${esc(p.name)}</h3><p data-card-description>${esc(p.description)}</p><div class="card-actions"><button type="button" class="choose-project" data-choose="${esc(p.id)}" aria-pressed="${p.id === data.defaultProject}" aria-label="Fokus: ${esc(p.name)}">${p.id === data.defaultProject ? 'Dein Fokus ✓' : 'Als Fokus wählen'}</button><a class="card-open" data-card-open href="${esc(p.entry)}">Öffnen <span aria-hidden="true">↗</span></a></div></article>`).join('\n');
const indexPath = path.join(root, 'index.html');
const index = fs.readFileSync(indexPath, 'utf8');
const markers = /        <!-- SPACE_PROJECTS_START -->[\s\S]*?        <!-- SPACE_PROJECTS_END -->/;
if (!markers.test(index)) throw new Error('Static atlas marker missing.');
fs.writeFileSync(indexPath, index.replace(markers, '        <!-- SPACE_PROJECTS_START -->\n' + cards + '\n        <!-- SPACE_PROJECTS_END -->'));
fs.writeFileSync(path.join(root, 'space-data.js'), '/* Generated from data/juris-space.json by tools/build-space.cjs. */\nwindow.JurisSpaceData = ' + JSON.stringify(data).replace(/</g,'\\u003c') + ';\n');
console.log(JSON.stringify({state:'STATIC_ATLAS_BUILT',repositories:data.repositoryCount,sites:data.siteCount,cards:projects.length,sourceSha256:crypto.createHash('sha256').update(dataBytes).digest('hex')}));
